# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4A_UOxr7Hzd9LBRPK51q6uQPFa7zeWg
"""

import numpy as np
import pandas as pd
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

df=pd.read_csv("/content/Unemployment_Rate_upto_11_2020.csv")
df.head()

df.shape

df.info()

"""descrining data"""

df.describe()

x=df['Region']
x

y=df[' Estimated Unemployment Rate (%)']
y

df2=df.iloc[:,3]
df2

"""importing libraries"""

import plotly.express as px
import matplotlib.pyplot as plt

"""analyzing data by barcode"""

fg = px.bar(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment rate',animation_frame=' Date',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.bar(df,x='Region.1',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment rate',animation_frame=' Date',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

"""Analyzing data by boxplot"""

fg = px.box(df,x='Region.1',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment rate',animation_frame=' Date',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.scatter(df,x='Region.1',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment rate',animation_frame=' Date',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

"""Analzing data by histogram"""

fg = px.histogram(df,x='Region.1',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment rate',animation_frame=' Date',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()